site_name: Python Madrid Learn Doc
site_url: https://bameda.github.io/python-madrid-learn-doc/
site_description: Recopilatorio del grupo python-madrid-learn de documentación, manuales y tutoriales.
site_author: Python Madrid
repo_url: https://github.com/bameda/python-madrid-learn-doc
copyright: <a href="https://creativecommons.org/publicdomain/zero/1.0/"><img src="http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg" alt="CC0" data-canonical-src="http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg" style="max-width:100%;"></a><p>Y este es nuestro <a href="https://github.com/bameda/python-madrid-learn-doc/blob/master/COC.md" alt="Ver el Código de Conducta">Código de Conducta</a>.</p>
extra_css:
    - extra.css
markdown_extensions:
    - def_list
